### ISSUE TITLE
Le rond-point

### ISSUE THREAD

**Issue by LeRondPoint** [ellipsesynergie/builtinsaglac#19]
Spécialisé en dévelopement d'applications mobile iOS et Android avec Xamarin

lerondpont.net

Merci

**Comment by dominicmartineau** [comment]
@LeRondPoint Je vous invite à ajouter vous même votre logo à la suite de Bloobuzz et de faire un pull request :)

**Comment by LeRondPoint** [comment]
Ah bien sûr!
